# Generated by Django 3.2.15 on 2022-09-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20220929_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='defense',
            new_name='defence',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='atack',
            new_name='strength',
        ),
    ]
