# Generated by Django 2.2.24 on 2022-10-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20221003_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evos', to='pokemon_entities.Pokemon', verbose_name='Предыдущая эволюция покемона'),
        ),
    ]
